runtime: custom
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
 python_version: 3

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2

resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 25
